spring.application.name=java_starter
server.port=8001
spring.datasource.url=jdbc:postgresql://localhost:5432/starter
spring.datasource.username=root
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000
